-- MySQL Script generated by MySQL Workbench
-- ven. 13 avril 2018 09:22:53 +04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema product_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema product_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `product_project` DEFAULT CHARACTER SET utf8 ;
USE `product_project` ;

-- -----------------------------------------------------
-- Table `product_project`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_project`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `phone` INT NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `firstName` VARCHAR(200) NOT NULL,
  `lastName` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `product_project`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_project`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`, `userId`),
  INDEX `fk_carts_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_carts_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `product_project`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `product_project`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_project`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `isActive` TINYINT(1) NOT NULL DEFAULT 0,
  `categoryId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_CATEGORY_CATEGORY1_idx` (`categoryId` ASC),
  CONSTRAINT `fk_CATEGORY_CATEGORY1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `product_project`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `product_project`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_project`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `categoryId` INT NOT NULL,
  PRIMARY KEY (`id`, `categoryId`),
  INDEX `fk_products_categories1_idx` (`categoryId` ASC),
  CONSTRAINT `fk_products_categories1`
    FOREIGN KEY (`categoryId`)
    REFERENCES `product_project`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `product_project`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_project`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `message` TEXT NOT NULL,
  `productId` INT NOT NULL,
  `userId` INT NOT NULL,
  PRIMARY KEY (`id`, `productId`, `userId`),
  INDEX `fk_comments_products1_idx` (`productId` ASC),
  INDEX `fk_comments_users1_idx` (`userId` ASC),
  CONSTRAINT `fk_comments_products1`
    FOREIGN KEY (`productId`)
    REFERENCES `product_project`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`userId`)
    REFERENCES `product_project`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `product_project`.`carts_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product_project`.`carts_items` (
  `cartId` INT NOT NULL,
  `productId` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`cartId`, `productId`),
  INDEX `fk_carts_has_products_products1_idx` (`productId` ASC),
  INDEX `fk_carts_has_products_carts1_idx` (`cartId` ASC),
  CONSTRAINT `fk_carts_has_products_carts1`
    FOREIGN KEY (`cartId`)
    REFERENCES `product_project`.`carts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carts_has_products_products1`
    FOREIGN KEY (`productId`)
    REFERENCES `product_project`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
